spring.application.name=billingsoftware


# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_app
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate JPA settings

# auto update when u made changes in the code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.servlet.context-path=/api/v1.0


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


jwt.secret.key=thisismysecretkeyforourgroupproject

